import * as z from 'zod';

export const MetadataSchema = z.object({
  Make: z.string().optional(),
  Model: z.string().optional(),
  XResolution: z.number().optional(),
  YResolution: z.number().optional(),
  ResolutionUnit: z.string().optional(),
  Software: z.string().optional(),
  ModifyDate: z.date().optional(),
  HostComputer: z.string().optional(),
  YCbCrPositioning: z.number().optional(),
  ExposureTime: z.number().optional(),
  FNumber: z.number().optional(),
  ExposureProgram: z.string().optional(),
  ISO: z.number().optional(),
  ExifVersion: z.string().optional(),
  DateTimeOriginal: z.date().optional(),
  CreateDate: z.date().optional(),
  OffsetTime: z.string().optional(),
  OffsetTimeOriginal: z.string().optional(),
  OffsetTimeDigitized: z.string().optional(),
  //   ComponentsConfiguration: {
  //     "0": 1,
  //     "1": 2,
  //     "2": 3,
  //     "3": 0,
  //   },
  ShutterSpeedValue: z.number().optional(),
  ApertureValue: z.number().optional(),
  BrightnessValue: z.number().optional(),
  ExposureCompensation: z.number().optional(),
  MeteringMode: z.string().optional(),
  Flash: z.string().optional(),
  FocalLength: z.number().optional(),
  //   SubjectArea: {
  //     "0": 2011,
  //     "1": 1510,
  //     "2": 1107,
  //     "3": 662,
  //   },
  SubSecTimeOriginal: z.string().optional(),
  SubSecTimeDigitized: z.string().optional(),
  FlashpixVersion: z.string().optional(),
  ColorSpace: z.number().optional(),
  ExifImageWidth: z.number().optional(),
  ExifImageHeight: z.number().optional(),
  SensingMethod: z.string().optional(),
  SceneType: z.string().optional(),
  ExposureMode: z.string().optional(),
  WhiteBalance: z.string().optional(),
  FocalLengthIn35mmFormat: z.number().optional(),
  SceneCaptureType: z.string().optional(),
  LensInfo: z.number().array().optional(),
  LensMake: z.string().optional(),
  LensModel: z.string().optional(),
  CompositeImage: z.string().optional(),
  GPSLatitudeRef: z.string().optional(),
  GPSLatitude: z.number().array().optional(),
  GPSLongitudeRef: z.string().optional(),
  GPSLongitude: z.number().array().optional(),
  //   GPSAltitudeRef: {
  //     "0": 0,
  //   },
  GPSAltitude: z.number().optional(),
  GPSTimeStamp: z.string().optional(),
  GPSSpeedRef: z.string().optional(),
  GPSSpeed: z.number().optional(),
  GPSImgDirectionRef: z.string().optional(),
  GPSImgDirection: z.number().optional(),
  GPSDestBearingRef: z.string().optional(),
  GPSDestBearing: z.number().optional(),
  GPSDateStamp: z.string().optional(),
  GPSHPositioningError: z.number().optional(),
  latitude: z.number().optional(),
  longitude: z.number().optional(),
});

export type Metadata = z.infer<typeof MetadataSchema>;
